### ISSUE TITLE
[Bug] A way for custom enemies to be stomped by boxes but not players

### ISSUE THREAD

**Issue by ncrecc** [HugoBDesigner/Mari0-Community-Edition#55]
As of the moment "killedbyboxes": true, "stompable": false just means any boxes dropped on the enemy will bounce up and down, making the stomp noise but not actually killing the enemy.

I'd like for a way to configure a CE such that when a player steps on it, the player just uses the enemy as ground _with the player nor the enemy being harmed in the process_, but when a cube steps on it, the enemy is stomped and killed. I don't believe that's currently possible.

**Comment by HugoBDesigner** [comment]
I'm treating this as a bug because it doesn't make sense that one property depends on the other. They should have been independent all along.

**Comment by HugoBDesigner** [comment]
Fixed in #63
