### ISSUE TITLE
[Suggestion] Animations to let players use other portal IDs

### ISSUE THREAD

**Issue by ncrecc** [HugoBDesigner/Mari0-Community-Edition#58]
Add a condition "portal id of [everyone/player 1/player 2/player 3/player 4] is [1/2/3/4/5/6/7/8]"
Add an action "switch portal id of [everyone/player 1/player 2/player 3/player 4] to [1/2/3/4/5/6/7/8]"

This would open up room for puzzles requiring two pairs of linked portals instead of just one. And other, more useful stuff, hopefully.

**Comment by villager103** [comment]
To go with this, a feature that allows mapmakers to change the portal colors of all sets on a per-mappack basis would be great for this, because having them all be the same color would be confusing.

**Comment by HugoBDesigner** [comment]
Moved to #59
