### ISSUE TITLE
[Bug] Completing World X-4 always takes you to the next world, even if Worlds X-5, X-6 and so on exist.

### ISSUE THREAD

**Issue by villager103** [HugoBDesigner/Mari0-Community-Edition#61]

**Comment by WillWare** [comment]
I believe this is intended behavior, but maybe it could be added as a per-mappack setting.

**Comment by villager103** [comment]
For 1.6, sure. But in SE, you can add as many levels to a world as you want, which makes this feature useless and restrictive, forcing you into having only 4 levels per-world when it's possible to create as many as you want now.

The game should only take you to the next world if you beat the last level of that world, which would allow for both classic 4-level worlds, and worlds with more than 4 levels to be made.

**Comment by WillWare** [comment]
Worlds can now be arbitrarily large, and the game will advance to the next world when the next numbered level doesn't exist. Examples:

- If 1-1, 1-2, 1-3, 1-4, and 1-5 all exist, the game will move on to world 2 after 1-5 is completed.
- If only 2-1 and 2-3 exist, the game will move on to world 3 after 2-1 is completed (ignoring 2-3).
