### ISSUE TITLE
[Contribution] SMB graphics with fixed spritesets

### ISSUE THREAD

**Issue by villager103** [HugoBDesigner/Mari0-Community-Edition#9]
If you didn't know, some of the graphics and enemies in Mari0 use incorrect spritesets. I made fixed versions of them, they are in [here.](https://www.dropbox.com/s/l6nq76xacmxbpbw/SE%20Bugfixes%20Contribution%201.rar?dl=0)

The A in "Special Edition" on the Mari0 logo was also 1 pixel wider than normal, so I fixed that too.

**Comment by HugoBDesigner** [comment]
[Implemented](https://github.com/HugoBDesigner/Mari0-Community-Edition/commit/aea79cd2db0fe38b02a0bd888470e067e128b6f9)
